#include "spectrum/overlay/overlay_api.h"
#include "common/ui_messages.h"

static const char notices_msg_blob[] =
    NETCHESSZX_UI_PHASE_CONNECTING "\0"
    NETCHESSZX_UI_PHASE_CONNECTED "\0"
    NETCHESSZX_UI_NOTICE_SELECT_OPTIONS "\0"
    NETCHESSZX_UI_PHASE_WAITING_OPPONENT_SHORT "\0"
    NETCHESSZX_UI_SPECTRUM_NOTICE_OPPONENT_READY_GO "\0"
    NETCHESSZX_UI_SPECTRUM_NOTICE_OPPONENT_READY_WAIT "\0"
    NETCHESSZX_UI_PHASE_OPPONENT_TURN "\0"
    NETCHESSZX_UI_NOTICE_GAME_NOT_STARTED "\0"
    NETCHESSZX_UI_SPECTRUM_CONFIRM_DISCONNECT "\0"
    NETCHESSZX_UI_SPECTRUM_CONFIRM_RESET "\0"
    NETCHESSZX_UI_SPECTRUM_CONFIRM_RESET_REQUEST "\0"
    NETCHESSZX_UI_SPECTRUM_CONFIRM_RESTART_REQUEST "\0"
    NETCHESSZX_UI_ERROR_RESET_REJECTED "\0"
    NETCHESSZX_UI_SPECTRUM_NOTICE_WAITING_ACK "\0"
    NETCHESSZX_UI_EVENT_GAME_STARTED "\0"
    /* Removed DRAW notice IDs 15..17 remain empty ABI tombstones. */
    "\0\0\0"
    NETCHESSZX_UI_SPECTRUM_CONFIRM_RESIGN "\0"
    NETCHESSZX_UI_SPECTRUM_CONFIRM_RESTART_GAME "\0"
    NETCHESSZX_UI_ERROR_ROOM_CONFLICT "\0"
    NETCHESSZX_UI_SPECTRUM_CONFIRM_TAKEBACK "\0"
    NETCHESSZX_UI_SPECTRUM_CONFIRM_TAKEBACK_REQUEST "\0"
    NETCHESSZX_UI_SPECTRUM_NOTICE_TAKEBACK_SENT "\0"
    NETCHESSZX_UI_SPECTRUM_NOTICE_TAKEBACK_DONE "\0"
    NETCHESSZX_UI_SPECTRUM_ERROR_TAKEBACK_REJECTED "\0"
    NETCHESSZX_UI_SPECTRUM_ERROR_NO_TAKEBACK "\0"
    NETCHESSZX_UI_SPECTRUM_EVENT_SAVE_OK "\0"
    NETCHESSZX_UI_SPECTRUM_EVENT_LOAD_OK "\0"
    NETCHESSZX_UI_SPECTRUM_ERROR_SAVE_FAIL "\0"
    NETCHESSZX_UI_SPECTRUM_ERROR_LOAD_FAIL "\0"
    NETCHESSZX_UI_SPECTRUM_CONFIRM_RESTORE_LOAD "\0"
    NETCHESSZX_UI_SPECTRUM_NOTICE_LOAD_WAITING "\0"
    NETCHESSZX_UI_SPECTRUM_NOTICE_LOADING "\0"
    NETCHESSZX_UI_SPECTRUM_NOTICE_LOAD_DECLINED "\0"
    NETCHESSZX_UI_SPECTRUM_ERROR_MOVE_REJECTED "\0"
    NETCHESSZX_UI_SPECTRUM_NOTICE_OPPONENT_STARTS "\0"
    NETCHESSZX_UI_SPECTRUM_NOTICE_STARTING "\0"
    NETCHESSZX_UI_SPECTRUM_ERROR_HOST_BUSY "\0"
    NETCHESSZX_UI_ERROR_BAD_IP "\0"
    NETCHESSZX_UI_ERROR_BAD_PORT "\0"
    NETCHESSZX_UI_ERROR_INVALID_MQTT_ROOM "\0"
    "INVALID TIMEZONE\0"
    NETCHESSZX_UI_ERROR_SET_LOAD_FAILED "\0"
    NETCHESSZX_UI_ERROR_CONFIG_INVALID "\0"
    NETCHESSZX_UI_PHASE_YOUR_TURN "\0"
    NETCHESSZX_UI_NOTICE_RESIGN_ALREADY_APPLIED "\0"
    NETCHESSZX_UI_ERROR_START_FAILED "\0"
    NETCHESSZX_UI_NOTICE_LOAD_CANCELLED "\0"
    NETCHESSZX_UI_NOTICE_TYPE_MOVE_CHAT "\0"
    NETCHESSZX_UI_ERROR_NO_OPPONENT "\0"
    NETCHESSZX_UI_ERROR_BAD_DIRECT_HELLO "\0"
    NETCHESSZX_UI_ERROR_BAD_COLOR "\0"
    NETCHESSZX_UI_ERROR_GAME_ALREADY_ACTIVE "\0"
    NETCHESSZX_UI_ERROR_START_REJECTED "\0"
    NETCHESSZX_UI_ERROR_RESTART_FAILED_GAME_OVER "\0"
    NETCHESSZX_UI_ERROR_BAD_START "\0"
    NETCHESSZX_UI_NOTICE_CONTROL_RESET_CANCELLED "\0"
    NETCHESSZX_UI_NOTICE_CONTROL_RESET_EXPIRED "\0"
    /* Removed DRAW timeout IDs 59..60 remain empty ABI tombstones. */
    "\0\0"
    NETCHESSZX_UI_NOTICE_WAITING_RESIGN_ACK "\0"
    NETCHESSZX_UI_NOTICE_RESTARTING_GAME "\0"
    NETCHESSZX_UI_PHASE_WAITING_HOST;

uint8_t notices_notify_msg_ovl(uint8_t *ctx) __z88dk_fastcall
{
    const char *msg;
    uint8_t id = ctx[SPECTRUM_OVL_CTX_GUI_MSG_ID];

    if (id >= SPECTRUM_GUI_MSG_COUNT) {
        return 0u;
    }
    msg = notices_msg_blob;
    while (id-- != 0u) {
        while (*msg++ != '\0') {
        }
    }
    if (*msg == '\0') {
        return 0u;
    }
    id = ctx[SPECTRUM_OVL_CTX_GUI_MSG_KIND];
    if (id == SPECTRUM_GUI_MSG_KIND_WAIT) {
        spectrum_gui_notify_persistent(msg);
    } else if (id == SPECTRUM_GUI_MSG_KIND_SUCCESS) {
        spectrum_gui_notify_success(msg);
    } else {
        spectrum_gui_notify(
            msg, (uint8_t)(id == SPECTRUM_GUI_MSG_KIND_ERROR));
    }
    return 1u;
}
