#ifndef NETCHESSZX_SPECTRUM_OVERLAY_CONTEXT_H
#define NETCHESSZX_SPECTRUM_OVERLAY_CONTEXT_H

#include <stdint.h>

#include "spectrum/lowram_map.h"

#define SPECTRUM_OVERLAY_CONTEXT_SIZE NETCHESSZX_LOWRAM_OVERLAY_CONTEXT_SIZE

/* Wire formats for byte-indexed overlay calls. Keep writer and reader using
   these offsets; abi-check guards the symbol/size, not per-entry fields. */
#define SPECTRUM_OVL_CTX_PTR_LO 0u
#define SPECTRUM_OVL_CTX_PTR_HI 1u

#define SPECTRUM_OVL_CTX_GUI_MOVE_PLY_LO 0u
#define SPECTRUM_OVL_CTX_GUI_MOVE_PLY_HI 1u
#define SPECTRUM_OVL_CTX_GUI_MOVE_TEXT_LO 2u
#define SPECTRUM_OVL_CTX_GUI_MOVE_TEXT_HI 3u
/* ADD_MOVE packs render in bit 0; bit 7 requests a row reservation. */
#define SPECTRUM_OVL_CTX_GUI_RENDER 4u
#define SPECTRUM_OVL_CTX_GUI_MOVE_AUTHOR 5u
#define SPECTRUM_OVL_GUI_MOVE_AUTHOR_VALID 0x80u
#define SPECTRUM_OVL_GUI_MOVE_AUTHOR_BLACK 0x01u
#define SPECTRUM_OVL_GUI_MOVE_AUTHOR_UNKNOWN 0u

#define SPECTRUM_OVL_CTX_GUI_CHAT_WHO 0u
#define SPECTRUM_OVL_CTX_GUI_CHAT_TEXT_LO 1u
#define SPECTRUM_OVL_CTX_GUI_CHAT_TEXT_HI 2u

#define SPECTRUM_OVL_CTX_GUI_MSG_ID 0u
#define SPECTRUM_OVL_CTX_GUI_MSG_KIND 1u

#define SPECTRUM_OVL_CTX_INPUT_KEY 0u
#define SPECTRUM_OVL_CTX_INPUT_CMD_TEXT_LO 0u
#define SPECTRUM_OVL_CTX_INPUT_CMD_TEXT_HI 1u
#define SPECTRUM_OVL_CTX_INPUT_CMD_ARG_LO 2u
#define SPECTRUM_OVL_CTX_INPUT_CMD_ARG_HI 3u
#define SPECTRUM_OVL_CTX_SAVELOAD_NAME_LO 0u
#define SPECTRUM_OVL_CTX_SAVELOAD_NAME_HI 1u
#define SPECTRUM_OVL_CTX_SAVELOAD_BUF_LO 2u
#define SPECTRUM_OVL_CTX_SAVELOAD_BUF_HI 3u
#define SPECTRUM_OVL_CTX_SAVELOAD_RESULT 4u
#define SPECTRUM_OVL_CTX_CONFIG_STAGE 5u

#define SPECTRUM_CONFIG_SAVE_STAGE_OK 0u
#define SPECTRUM_CONFIG_SAVE_STAGE_DATA 1u
#define SPECTRUM_CONFIG_SAVE_STAGE_DIR_CLOSE 2u
#define SPECTRUM_CONFIG_SAVE_STAGE_DIR_CREATE 3u
#define SPECTRUM_CONFIG_SAVE_STAGE_DIR_VERIFY 4u
#define SPECTRUM_CONFIG_SAVE_STAGE_OLD_CLOSE 5u
#define SPECTRUM_CONFIG_SAVE_STAGE_FILE_CREATE 6u
#define SPECTRUM_CONFIG_SAVE_STAGE_FILE_WRITE 7u
#define SPECTRUM_CONFIG_SAVE_STAGE_FILE_CLOSE 8u
#define SPECTRUM_CONFIG_SAVE_STAGE_FILE_COMMIT 9u

#define SPECTRUM_OVL_CTX_RESTORE_SNAP_LO 0u
#define SPECTRUM_OVL_CTX_RESTORE_SNAP_HI 1u
#define SPECTRUM_OVL_CTX_RESTORE_META_LO 2u
#define SPECTRUM_OVL_CTX_RESTORE_META_HI 3u
#define SPECTRUM_OVL_CTX_RESTORE_TEXT_LO 4u
#define SPECTRUM_OVL_CTX_RESTORE_TEXT_HI 5u
#define SPECTRUM_OVL_CTX_RESTORE_CHUNK 6u

/* Historical RULES play/check context remains declared for ABI compatibility;
   both entries are fail-closed tombstones and no product caller writes it. */
#define SPECTRUM_OVL_CTX_HINTS_BOARD_LO 0u
#define SPECTRUM_OVL_CTX_HINTS_BOARD_HI 1u
#define SPECTRUM_OVL_CTX_HINTS_SIDE_TO_MOVE 2u
#define SPECTRUM_OVL_CTX_HINTS_SQUARE 3u
#define SPECTRUM_OVL_CTX_HINTS_CASTLE 4u
#define SPECTRUM_OVL_CTX_HINTS_EP 5u
#define SPECTRUM_OVL_CTX_RULES_RESTORE_SNAP_LO 0u
#define SPECTRUM_OVL_CTX_RULES_RESTORE_SNAP_HI 1u
#define SPECTRUM_OVL_CTX_RULES_RESTORE_RESULT 2u

#define SPECTRUM_OVL_SAVELOAD_OK 0u
#define SPECTRUM_OVL_SAVELOAD_ERR_NAME 1u
#define SPECTRUM_OVL_SAVELOAD_ERR_OPEN 2u
#define SPECTRUM_OVL_SAVELOAD_ERR_IO 3u
#define SPECTRUM_OVL_SAVELOAD_ERR_DATA 4u
#define SPECTRUM_OVL_SAVELOAD_ERR_MISSING 5u

#define SPECTRUM_OVL_CTX_FILEUI_KEY 0u
#define SPECTRUM_OVL_CTX_FILEUI_SEL 1u
#define SPECTRUM_OVL_CTX_FILEUI_ACTION 3u
#define SPECTRUM_OVL_CTX_FILEUI_NAME_LO 4u
#define SPECTRUM_OVL_CTX_FILEUI_NAME_HI 5u
#define SPECTRUM_OVL_CTX_FILEUI_PAGE_LO 6u
#define SPECTRUM_OVL_CTX_FILEUI_PAGE_HI 7u

#define SPECTRUM_OVL_FILEUI_ACT_NONE 0u
#define SPECTRUM_OVL_FILEUI_ACT_LOAD 1u
#define SPECTRUM_OVL_FILEUI_ACT_SAVE 2u
#define SPECTRUM_OVL_FILEUI_ACT_ERASE 3u
#define SPECTRUM_OVL_FILEUI_ACT_FAIL 0xffu
#define SPECTRUM_OVL_CTX_PREFLIGHT_OK 0u
#define SPECTRUM_OVL_CTX_PREFLIGHT_RETRY 1u
#define SPECTRUM_OVL_CTX_PREFLIGHT_QUIET 2u
#define SPECTRUM_OVL_PREFLIGHT_RETRY_DEFAULT 0u
#define SPECTRUM_OVL_PREFLIGHT_RETRY_AGAIN 1u

#define SPECTRUM_OVL_CTX_STATUS_PHASE 0u
#define SPECTRUM_OVL_STATUS_LINE_TEXT_SIZE 53u
#define SPECTRUM_OVL_STATUS_LINE_SIZE (SPECTRUM_OVL_STATUS_LINE_TEXT_SIZE + 1u)

#define SPECTRUM_OVL_CTX_SETUP_KEY 0u
#define SPECTRUM_OVL_CTX_SETUP_FORCE_LO 1u
#define SPECTRUM_OVL_CTX_SETUP_FORCE_HI 2u
#define SPECTRUM_OVL_CTX_SETUP_CLEAR_FROM 3u
#define SPECTRUM_OVL_CTX_SETUP_ACTION 4u
#define SPECTRUM_OVL_CTX_SETUP_NOTICE 5u
#define SPECTRUM_OVL_CTX_SETUP_FLAGS 6u

#define SPECTRUM_OVL_SETUP_FLAG_RENDER 0x01u
#define SPECTRUM_OVL_SETUP_FLAG_PAINT 0x02u
#define SPECTRUM_OVL_SETUP_FLAG_EDIT 0x04u
#define SPECTRUM_OVL_SETUP_FLAG_SUPPRESS 0x08u

#define SPECTRUM_OVL_SETUP_ACTION_NONE 0u
#define SPECTRUM_OVL_SETUP_ACTION_BOARD 1u
#define SPECTRUM_OVL_SETUP_ACTION_SET 2u
#define SPECTRUM_OVL_SETUP_ACTION_START 3u
#define SPECTRUM_OVL_SETUP_ACTION_SAVE 4u

#define SPECTRUM_OVL_SETUP_NOTICE_NONE 0u
#define SPECTRUM_OVL_SETUP_NOTICE_SELECT 1u
#define SPECTRUM_OVL_SETUP_NOTICE_PENDING 2u
#define SPECTRUM_OVL_SETUP_NOTICE_BAD_IP 3u
#define SPECTRUM_OVL_SETUP_NOTICE_BAD_ROOM 4u
#define SPECTRUM_OVL_SETUP_NOTICE_BAD_PORT 5u
#define SPECTRUM_OVL_SETUP_NOTICE_BAD_TIMEZONE 6u

/* Resident code writes this buffer, overlay entries mutate it, then resident
   code reads it again. Keep it volatile so C never caches values across the
   overlay call boundary. */
#define spectrum_overlay_context ((volatile uint8_t *)NETCHESSZX_LOWRAM_OVERLAY_CONTEXT_ADDR)

#endif
