#ifndef NETCHESSZX_SPECTRUM_SESSION_TIMING_H
#define NETCHESSZX_SPECTRUM_SESSION_TIMING_H

#include <stdint.h>

/* Session counters advance once per empty transport poll. */
#ifdef NETCHESSZX_SPECTRANEXT
#define NETCHESSZX_SESSION_DIRECT_EMPTY_POLL_FRAMES 1u
#else
#define NETCHESSZX_SESSION_DIRECT_EMPTY_POLL_FRAMES 2u
#endif
#define NETCHESSZX_SESSION_MQTT_EMPTY_POLL_FRAMES 2u

#define NETCHESSZX_SESSION_POLLS_CEIL(numerator, denominator, hz, frames) \
    ((uint16_t)((((uint16_t)(numerator) * (uint16_t)(hz)) + \
                 ((uint16_t)(denominator) * (uint16_t)(frames)) - 1u) / \
                ((uint16_t)(denominator) * (uint16_t)(frames))))

#define NETCHESSZX_SESSION_DIRECT_3S_POLLS_AT(hz) \
    NETCHESSZX_SESSION_POLLS_CEIL(3u, 1u, (hz), \
                                  NETCHESSZX_SESSION_DIRECT_EMPTY_POLL_FRAMES)
#define NETCHESSZX_SESSION_DIRECT_REPLY_POLLS_AT(hz) \
    NETCHESSZX_SESSION_POLLS_CEIL(5u, 2u, (hz), \
                                  NETCHESSZX_SESSION_DIRECT_EMPTY_POLL_FRAMES)
#define NETCHESSZX_SESSION_MQTT_REPLY_POLLS_AT(hz) \
    NETCHESSZX_SESSION_POLLS_CEIL(5u, 2u, (hz), \
                                  NETCHESSZX_SESSION_MQTT_EMPTY_POLL_FRAMES)
#define NETCHESSZX_SESSION_DIRECT_GRACE_POLLS_AT(hz) \
    NETCHESSZX_SESSION_POLLS_CEIL(300u, 1u, (hz), \
                                  NETCHESSZX_SESSION_DIRECT_EMPTY_POLL_FRAMES)
#define NETCHESSZX_SESSION_MQTT_4_8S_POLLS_AT(hz) \
    NETCHESSZX_SESSION_POLLS_CEIL(24u, 5u, (hz), \
                                  NETCHESSZX_SESSION_MQTT_EMPTY_POLL_FRAMES)
#define NETCHESSZX_SESSION_MQTT_GRACE_POLLS_AT(hz) \
    NETCHESSZX_SESSION_POLLS_CEIL(300u, 1u, (hz), \
                                  NETCHESSZX_SESSION_MQTT_EMPTY_POLL_FRAMES)

#ifdef NETCHESSZX_NEXT
extern uint8_t net_uart_direct_idle_ticks;
#define NETCHESSZX_SESSION_DIRECT_3S_POLLS net_uart_direct_idle_ticks
#define NETCHESSZX_SESSION_IS_60HZ \
    (net_uart_direct_idle_ticks == \
     NETCHESSZX_SESSION_DIRECT_3S_POLLS_AT(60u))
#else
#define NETCHESSZX_SESSION_DIRECT_3S_POLLS \
    NETCHESSZX_SESSION_DIRECT_3S_POLLS_AT(50u)
#define NETCHESSZX_SESSION_IS_60HZ 0u
#endif

#define NETCHESSZX_SESSION_DIRECT_3S_POLLS_FROM_NEXTREG(peripheral_1) \
    ((uint8_t)(((peripheral_1) & 0x04u) != 0u \
        ? NETCHESSZX_SESSION_POLLS_CEIL(3u, 1u, 60u, 2u) \
        : NETCHESSZX_SESSION_POLLS_CEIL(3u, 1u, 50u, 2u)))
#define NETCHESSZX_SESSION_DIRECT_REPLY_POLLS \
    (NETCHESSZX_SESSION_IS_60HZ \
         ? NETCHESSZX_SESSION_DIRECT_REPLY_POLLS_AT(60u) \
         : NETCHESSZX_SESSION_DIRECT_REPLY_POLLS_AT(50u))
#define NETCHESSZX_SESSION_MQTT_REPLY_POLLS \
    (NETCHESSZX_SESSION_IS_60HZ \
         ? NETCHESSZX_SESSION_MQTT_REPLY_POLLS_AT(60u) \
         : NETCHESSZX_SESSION_MQTT_REPLY_POLLS_AT(50u))
#define NETCHESSZX_SESSION_DIRECT_GRACE_POLLS \
    (NETCHESSZX_SESSION_IS_60HZ \
         ? NETCHESSZX_SESSION_DIRECT_GRACE_POLLS_AT(60u) \
         : NETCHESSZX_SESSION_DIRECT_GRACE_POLLS_AT(50u))
#define NETCHESSZX_SESSION_MQTT_4_8S_POLLS \
    (NETCHESSZX_SESSION_IS_60HZ \
         ? NETCHESSZX_SESSION_MQTT_4_8S_POLLS_AT(60u) \
         : NETCHESSZX_SESSION_MQTT_4_8S_POLLS_AT(50u))
#define NETCHESSZX_SESSION_MQTT_GRACE_POLLS \
    (NETCHESSZX_SESSION_IS_60HZ \
         ? NETCHESSZX_SESSION_MQTT_GRACE_POLLS_AT(60u) \
         : NETCHESSZX_SESSION_MQTT_GRACE_POLLS_AT(50u))

#endif
