#!/usr/bin/env python3
"""Generate private resident definitions used by the Next extension bank."""

from __future__ import annotations

import sys
from pathlib import Path

from gen_overlay_defs import parse_map


REQUIRED_SYMBOLS = (
    "_netchesszx_board_dark_attr",
    "_netchesszx_board_light_attr",
    "_netchesszx_board_theme_index",
    "_netchesszx_hinted_rows",
    "_netchesszx_local_color",
    "_netchesszx_movement_hints",
    "_setup_cursor",
    "_setup_edit_row",
    "_setup_room_editing",
    "_spectrum_fileui_count",
    "_spectrum_frame_wait",
    "_spectrum_gui_board_flipped",
    "_spectrum_gui_edit_tick",
    "_spectrum_gui_redraw_square",
    "_spectrum_gui_tick",
    "_spectrum_overlay_exec",
    "_spectrum_overlay_exec_cached",
    "_spectrum_uart_background_pump",
    "banner_shine_state",
    "board_col",
    "board_iter",
    "board_ptr",
    "board_row",
    "board_theme_hint_inks",
    "call_overlay_ae",
    "compute_square_bc",
    "conn_attr",
    "current_attr",
    "draw_icon_sprite_at_tmp",
    "key_last",
    "key_repeat_timer",
    "key_suppress",
    "mark_mode",
    "marker_slot_flags",
    "marker_slot_squares",
    "move_ptr",
    "nextreg_read",
    "nextreg_write",
    "notice_ptr",
    "piece_char",
    "piece_col",
    "piece_row",
    "piece_scan",
    "render_hint_common",
    "scaled_col",
    "scaled_row",
    "spectrum_input_queue_clear",
    "spectrum_input_queue_latch",
    "sprite_ptr",
    "square_parity",
    "status_ptr",
    "text_ptr",
    "tmp_attr",
    "tmp_char",
    "tmp_col",
    "tmp_row",
    "tmp_scan",
)


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print("Usage: gen_next_graphics_defs.py <map_file>", file=sys.stderr)
        return 2

    symbols = parse_map(Path(argv[1]))
    missing = [name for name in REQUIRED_SYMBOLS if name not in symbols]
    if missing:
        print("Missing symbols: " + ", ".join(missing), file=sys.stderr)
        return 1

    print(";; AUTO-GENERATED by tools/gen_next_graphics_defs.py -- DO NOT EDIT")
    for name in REQUIRED_SYMBOLS:
        print(f"PUBLIC {name}")
        print(f"DEFC {name} = ${symbols[name]:04X}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
